- name: Ceph Cluster
  hosts: localhost
  connection: localhost
  tasks:

  #
  # Provision LXC Containers For Development.
  #

  - name: Provision LXC Containers (cluster nodes)
    lxc_container:
      name: "{{ item }}"
      container_log: true
      template: ubuntu
      state: started
      template_options: --release trusty
    with_items:
    - admin-node
    - cluster-node-1
    - cluster-node-2
    - cluster-node-3
    register: nodes

  - debug: var=item
    with_items: nodes.results

  - name: Add Admin Node Host To Inventory
    add_host: hostname=admin-node
              ansible_ssh_host={{ item.lxc_container.ips[0] }}
              ansible_ssh_user=ubuntu
              ansible_ssh_pass=ubuntu
              ansible_become_user=root
              ansible_become_pass=ubuntu
              groups=cluster,admin
    with_items: nodes.results[0]

  - name: Add Node Hosts To Inventory
    add_host: hostname={{ item.lxc_container.init_pid }}
              ansible_ssh_host={{ item.lxc_container.ips[0] }}
              ansible_ssh_user=ubuntu
              ansible_ssh_pass=ubuntu
              ansible_become_user=root
              ansible_become_pass=ubuntu
              groups=cluster,nodes
    with_items: nodes.results[1:]

- name: Install ceph Packages
  hosts: cluster
  roles:
  - ceph-deploy