- name: Create user if required and generate keypair.
  user: name=ceph-admin comment="Ceph Admin" generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
  register: id_rsa

- debug: var=id_rsa
